language: python

python:
    - 2.6
    - 2.7
    - 3.3
    - 3.4
    - "pypy"

install:
    - python setup.py build install
    - pip install -r dev_requirements.txt

script: make test-with-coverage


